language: python
python: 
  - 3.4
  - 3.5
  - 3.6

install: pip install tox

# http://stackoverflow.com/a/42309035
script: 
  - tox -e $(echo py${TRAVIS_PYTHON_VERSION} | tr -d . | sed -e 's/pypypy/pypy/') 
  - tox -e lint
  - tox -e docs

after_failure: cat .tox/log/tox-*.log

deploy:
  provider: pypi
  user: n8henrie
  password:
    # travis encrypt --add deploy.password
    secure: "Your encrypted password"
  distributions: "sdist bdist_wheel"
  on:
    branch: master
    tags: true
